<?php

/**
 * @file
 * Contains sendgrid_marketing.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Mail\MailFormatHelper;

/**
 * Implements hook_help().
 */
function sendgrid_marketing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sendgrid_marketing module.
    case 'help.page.sendgrid_marketing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create and send newsletter via SendGrid Marketing Campaigns') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function sendgrid_marketing_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'sendgrid_campaign') {
    $response = sendgrid_marketing_create_campaign($entity);

    if (!empty($response) && $response->statusCode() == 201) {
      $data = $response->body();
      $data = json_decode($data);

      $entity->field_sendgrid_campaign_id->value = $data->id;
      $entity->setNewRevision(FALSE);
      $entity->save();
    }

  }
}

/**
 * Create SendGrid Campaign from Newsletter node.
 */
function sendgrid_marketing_create_campaign($entity) {
  $config = \Drupal::config('sendgrid_marketing.settings');
  $sendgrid_api_key = $message = $config->get('sendgrid_api_key');
  $sg = new \SendGrid($sendgrid_api_key);

  // @todo Add support for Segments.
  //$segment_ids = [];

  $sender_id = $config->get('sendgrid_sender_id');

  // @todo Add support for multiple lists
  //$list_ids = !empty($list) ? [$list] : [$config->get('sendgrid_list_id')];
  $list_ids = [$config->get('sendgrid_list_id')];

  $suppression_group_id = $config->get('sendgrid_suppression_group_id');

  $html_content = $entity->sendgrid_marketing_body->value;
  $plain_content = MailFormatHelper::htmlToText($html_content);
  // @todo Add Header/Footer settings with validation for existing [unsubscribe] token.

  $request_body = array(
    'custom_unsubscribe_url' => '',
    'html_content' => $html_content,
    'list_ids' => $list_ids,
    'plain_content' => $plain_content,
    // @todo Add support for Segment ids.
    //'segment_ids' => $segment_ids,
    'sender_id' => $sender_id,
    'subject' => $entity->label(),
    'suppression_group_id' => $suppression_group_id,
    'title' => $entity->label(),
  );

  $ip_pool = $config->get('sendgrid_ip_pool');
  if (!empty($ip_pool)) {
    $request_body['ip_pool'] = $ip_pool;
  }

  // @todo Add support for multiple categories.
  $category = $config->get('sendgrid_category');
  if (!empty($category)) {
    $request_body['categories'] = [$category];
  }

  $response = $sg->client->campaigns()->post($request_body);

  return $response;
}

// @todo Add notifications about required settings fields on Adding Campaign form.